fn main() -> Result<(), Box<dyn std::error::Error>> {
  tonic_build::configure().out_dir("src/proto/").compile(
    &[
      "src/proto/auth.proto",
      "src/proto/prelude.proto",
      "src/proto/user.proto",
      "src/proto/customer.proto",
      "src/proto/email.proto",
      "src/proto/product.proto",
      "src/proto/source.proto",
      "src/proto/cash.proto",
      "src/proto/purchase.proto",
      "src/proto/invoice.proto",
      "src/proto/document.proto",
      "src/proto/pricing.proto",
      "src/proto/upl.proto",
      "src/proto/procurement.proto",
      "src/proto/inventory.proto",
      "src/proto/stock.proto",
      "src/proto/commitment.proto",
      "src/proto/loyalty.proto",
      "src/proto/latex.proto",
      "src/proto/sku_image.proto",
      "src/proto/sku_image_processer.proto",
    ],
    &["src/proto"],
  )?;
  Ok(())
}
